#!/usr/bin/env -S ruby --disable=gems
# frozen_string_literal: true

require "fileutils"
require "yaml"

ROOT = File.expand_path("..", __dir__)
SOURCE_DIR = File.join(ROOT, "packages/ai/.config/kilo/agents")
OPENCODE_DIR = File.join(ROOT, "packages/ai/.config/opencode/agents")
CODEX_DIR = File.join(ROOT, "packages/ai/.codex/agents")
CODEX_SKILLS_DIR = File.join(ROOT, "packages/ai/.codex/skills")

# Represents one source Markdown agent definition.
Agent = Struct.new(:name, :path, :frontmatter, :prompt, keyword_init: true)

# Read one Kilo/OpenCode-style Markdown agent file.
def read_agent(path)
  text = File.read(path)
  match = text.match(/\A---\n(?<frontmatter>.*?)\n---\n(?<prompt>.*)\z/m)
  raise "missing YAML frontmatter: #{path}" unless match

  frontmatter = YAML.safe_load(
    match[:frontmatter],
    permitted_classes: [],
    aliases: false
  )

  Agent.new(
    name: File.basename(path, ".md"),
    path: path,
    frontmatter: frontmatter,
    prompt: match[:prompt]
  )
end

# Convert an OpenCode/Kilo model id into a Codex model id.
def codex_model(model)
  return nil if model.nil? || model.empty?

  model.start_with?("openai/") ? model.delete_prefix("openai/") : model
end

# Infer the strongest Codex sandbox setting that can be mapped safely.
def codex_sandbox(agent)
  edit = agent.frontmatter.dig("permission", "edit")
  edit == "deny" ? "read-only" : nil
end

# Escape a string for TOML basic strings.
def toml_string(value)
  value.inspect
end

# Format text as a TOML multiline literal string.
def toml_multiline_literal(value)
  raise "prompt for #{value.inspect} contains unsupported TOML literal delimiter" if value.include?("'''")

  "'''\n#{value.chomp}\n'''"
end

# Generate one Codex custom-agent TOML document.
def codex_toml(agent)
  description = agent.frontmatter.fetch("description")
  model = codex_model(agent.frontmatter["model"])
  sandbox = codex_sandbox(agent)

  lines = [
    "# Generated by scripts/generate-ai-agents.rb from #{agent.path.delete_prefix("#{ROOT}/")}.",
    "# Do not edit directly; update the source Markdown agent instead.",
    "name = #{toml_string(agent.name)}",
    "description = #{toml_string(description)}"
  ]
  lines << "model = #{toml_string(model)}" if model
  lines << "sandbox_mode = #{toml_string(sandbox)}" if sandbox
  lines << "developer_instructions = #{toml_multiline_literal(agent.prompt)}"
  lines.join("\n") + "\n"
end

# Generate a Codex skill from the primary Overseer agent.
def codex_skill(agent)
  description = agent.frontmatter.fetch("description")

  <<~MARKDOWN
    ---
    # Generated by scripts/generate-ai-agents.rb from #{agent.path.delete_prefix("#{ROOT}/")}.
    # Do not edit directly; update the source Markdown agent instead.
    name: #{agent.name}
    description: #{description.inspect}
    ---
    # #{agent.name}
    #{agent.prompt.strip}
  MARKDOWN
end

# Write the generated outputs for all agents.
def generate(agents, check:)
  outputs = {}

  agents.each do |agent|
    outputs[File.join(OPENCODE_DIR, "#{agent.name}.md")] = File.read(agent.path)
    outputs[File.join(CODEX_DIR, "#{agent.name}.toml")] = codex_toml(agent)
  end

  overseer = agents.find { |agent| agent.name == "overseer" }
  raise "missing overseer agent" unless overseer

  outputs[File.join(CODEX_SKILLS_DIR, "overseer/SKILL.md")] = codex_skill(overseer)

  changed = outputs.select { |path, content| !File.exist?(path) || File.read(path) != content }

  if check
    if changed.empty?
      puts "Generated OpenCode and Codex agents are up to date."
      return true
    end

    warn "Generated agents are stale:"
    changed.keys.sort.each { |path| warn "  #{path.delete_prefix("#{ROOT}/")}" }
    return false
  end

  FileUtils.mkdir_p(OPENCODE_DIR)
  FileUtils.mkdir_p(CODEX_DIR)
  FileUtils.mkdir_p(File.join(CODEX_SKILLS_DIR, "overseer"))

  outputs.each do |path, content|
    File.write(path, content)
  end

  puts "Generated #{agents.length} OpenCode agents in #{OPENCODE_DIR.delete_prefix("#{ROOT}/")}"
  puts "Generated #{agents.length} Codex agents in #{CODEX_DIR.delete_prefix("#{ROOT}/")}"
  puts "Generated Codex Overseer skill in #{CODEX_SKILLS_DIR.delete_prefix("#{ROOT}/")}/overseer"
  true
end

check = ARGV.delete("--check")
raise "unknown arguments: #{ARGV.join(" ")}" unless ARGV.empty?

agents = Dir[File.join(SOURCE_DIR, "*.md")].sort.map { |path| read_agent(path) }
exit(generate(agents, check: check) ? 0 : 1)
